### ISSUE TITLE
DecodePts::applyShiftEdit - Attempt to deference an invalid iterator

### ISSUE THREAD

**Issue by lixo6500** [nokiatech/heif#10]
In the line 177 of the file decodepts.hpp you have
`if (std::prev(it) != mMediaPts.cbegin() &&...`

I believe what you intended was
`if (it != mMediaPts.cbegin() &&...`

I happened by this bug when to use the C036.heic (found on your own repository) with the reader.

A simple
`HevcImageFileReader reader;`
`reader.initialize("C036.heic");`
is enough to reproduce the problem.

**Comment by nokiatech** [comment]
Resolved with v3.0
