### ISSUE TITLE
Build issues: snprintf not declared

### ISSUE THREAD

**Issue by Tosken1337** [nokiatech/heif#16]
Hi,

i wanted to build the library using windows with cmake and mingw.
cmake runs properly and when compiling the source using make i get an error when it comes to the
jsonLib:

D:\development\Libs\c++\heif-master\Srcs\jsonlib\jsoncpp.cpp:1035:70: error: 'snprintf' was not declared in this scope
   snprintf(buffer, sizeof(buffer), "Line %d, Column %d", line, column);

and so on.

Anyone has an idea what i am doing wrong?

Thanks
Sebastian

**Comment by nokiatech** [comment]
Resolved in v3.0. Jsonlib no longer part of code base.

**Comment by crb912** [comment]
Could you tell me how to build the library using windows with cmake and MinGw?
