### ISSUE TITLE
how to get camera make and camera model?

### ISSUE THREAD

**Issue by liuziangexit** [nokiatech/heif#19]
how to read Exif inside the heif file?

**Comment by liuziangexit** [comment]
i mean...something like this
![image](https://user-images.githubusercontent.com/15322450/30539315-71bdf24a-9ca4-11e7-9f43-f688907a978d.png)

**Comment by flemingm** [comment]
Good reference and tools for access data  stored in Meta data section is:
http://owl.phy.queensu.ca/~phil/exiftool/

Not CGIageSourceCopyPropertiesAtIndex() will return all meta data in the file. include EXIF, GPS, TIFF, and IPTC.  Apple documentation:

https://developer.apple.com/documentation/imageio/cgimageproperties

and sample code can be seen at:
https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_source/ikpg_source.html#//apple_ref/doc/uid/TP40005462-CH218-DontLinkElementID_9

**Comment by liuziangexit** [comment]
@flemingm thank you so much

**Comment by benuri** [comment]
Can this be done in a cross-platform way using the API in this repository?

**Comment by liuziangexit** [comment]
std::string read_heif_exif_raw(HevcImageFileReader& reader, const uint32_t& contextid)noexcept {
	try {
		if (reader.mMetaBoxInfo.empty())
			throw std::exception();

		auto iteminfo(*std::get<1>(*reader.mMetaBoxInfo.begin()).itemInfoMap.begin());
		if (DC::STR::toLower(std::get<1>(iteminfo).type) != "exif")
			return std::string();

		std::vector<uint8_t> exif_raw_data;
		reader.getItemData(contextid, std::get<0>(iteminfo), exif_raw_data);

		int exif_begin_offset = -1;
		for (auto it = 0; it < exif_raw_data.size(); it++)
			if (exif_raw_data[it] == 'E'&&exif_raw_data[it + 1] == 'x'&&exif_raw_data[it + 2] == 'i'&&exif_raw_data[it + 3] == 'f'&&exif_raw_data[it + 4] == 0 && exif_raw_data[it + 5] == 0) {
				exif_begin_offset = it;
				break;
			}
		if (exif_begin_offset == -1)
			throw std::exception("can not find \"EXIF\"");

		std::string return_this(exif_raw_data.begin() + exif_begin_offset, exif_raw_data.end());
		return return_this;
	}
	catch (...) {
		return std::string();
	}
}

**Comment by liuziangexit** [comment]
this code will work. hope it will help you.
