### ISSUE TITLE
OSX El Capitain - Compile Issue

### ISSUE THREAD

**Issue by garybruckheimer** [nokiatech/heif#2]
Tried to compile heir for OS X and got these errors during compiling process:

In file included from /heif/Srcs/common/hevcsampleentry.cpp:13:
/Users/gary/Desktop/raypack_heif/heif/Srcs/common/hevcsampleentry.hpp:46:18: error: 'writeBox' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual void writeBox(BitStream& bitstr);
                 ^
/heif/Srcs/common/visualsampleentrybox.hpp:66:18: note: overridden virtual function is here
    virtual void writeBox(BitStream& bitstr);
                 ^
In file included from /heif/Srcs/common/hevcsampleentry.cpp:13:
/heif/Srcs/common/hevcsampleentry.hpp:51:18: error: 'parseBox' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual void parseBox(BitStream& bitstr);
                 ^
/heif/Srcs/common/visualsampleentrybox.hpp:70:18: note: overridden virtual function is here
    virtual void parseBox(BitStream& bitstr);
                 ^
2 errors generated.

**Comment by juzzlin** [comment]
Disable -Winconsistent-missing-override by setting -Wno-inconsistent-missing-override or disable -Werror completely.

You might want to take a look at:
http://stackoverflow.com/questions/32626171/xcode-7-how-to-suppress-warning-overrides-a-member-function-but-is-not-marked

**Comment by garybruckheimer** [comment]
Yes, i have tried that, but there a bunch of other errors with clang compiler on OS X with the current code of heif.

In several classes i got this message:

/heif/Srcs/common/itemreferencebox.cpp:160:12: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move(references);
           
In the cpp i can see the std call:
std::vector<SingleItemTypeReferenceBox> ItemReferenceBox::getReferencesOfType(const std::string& type) const
{
    std::vector<SingleItemTypeReferenceBox> references;
    for (const auto& reference : mReferenceList)
    {
        if (reference.getType() == type)
        {
            references.push_back(reference);
        }
    }
    return std::move(references);
}

Currently i do not understand if its a multi return point issue of a conditional initialization problem that clang is not accepting here.

It seems that the OSX compilers can't support copy elision btw. (N)RVO.

Do you had this situation before? 

I think the move is in several cpp files and i do not want to fix it manual to get it compile btw. to get out of github repos. 

I try to compile it on wind, lnx and osx. Win and Lnx seems to work fine. OS X seems to be a problem 

Thanks for any help.

**Comment by lassehe** [comment]
Thanks for reporting this. I applied fixes for clang (3.8.0) warnings. Please check if it works now.
