### ISSUE TITLE
build fail in Centos 6.5

### ISSUE THREAD

**Issue by anbysure** [nokiatech/heif#25]
This is error log. please help me,thank you.

[root@baseline build]# cmake ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- System name       : Linux
-- Project Name      : HEIF
-- Project directory : /home/heif
-- Executables in    : /home/heif/Bins
-- File-list         : 
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heif/build
[root@baseline build]# make
/usr/bin/cmake -H/home/heif -B/home/heif/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/heif/build/CMakeFiles /home/heif/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/heif/build'
make -f Srcs/parser/h265parser/CMakeFiles/h265parser.dir/build.make Srcs/parser/h265parser/CMakeFiles/h265parser.dir/depend
make[2]: Entering directory `/home/heif/build'
cd /home/heif/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/heif /home/heif/Srcs/parser/h265parser /home/heif/build /home/heif/build/Srcs/parser/h265parser /home/heif/build/Srcs/parser/h265parser/CMakeFiles/h265parser.dir/DependInfo.cmake --color=
Scanning dependencies of target h265parser
make[2]: Leaving directory `/home/heif/build'
make -f Srcs/parser/h265parser/CMakeFiles/h265parser.dir/build.make Srcs/parser/h265parser/CMakeFiles/h265parser.dir/build
make[2]: Entering directory `/home/heif/build'
/usr/bin/cmake -E cmake_progress_report /home/heif/build/CMakeFiles 65
[  1%] Building CXX object Srcs/parser/h265parser/CMakeFiles/h265parser.dir/h265parser.cpp.o
cd /home/heif/build/Srcs/parser/h265parser && /usr/bin/c++    -std=c++0x -Wall -Wextra -Werror -Wno-missing-field-initializers -I/home/heif/Srcs/common -I/home/heif/Srcs/parser    -o CMakeFiles/h265parser.dir/h265parser.cpp.o -c /home/heif/Srcs/parser/h265parser/h265parser.cpp
/home/heif/Srcs/parser/h265parser/h265parser.cpp: In destructor ‘virtual H265Parser::~H265Parser()’:
/home/heif/Srcs/parser/h265parser/h265parser.cpp:38: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:43: error: expected primary-expression before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:43: error: expected ‘;’ before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:43: error: expected primary-expression before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:43: error: expected ‘)’ before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:43: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:48: error: expected primary-expression before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:48: error: expected ‘;’ before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:48: error: expected primary-expression before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:48: error: expected ‘)’ before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:48: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected primary-expression before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected ‘;’ before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected primary-expression before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected ‘)’ before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected primary-expression before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:52: error: expected ‘;’ before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp: In member function ‘bool H265Parser::initDisplayOrderArray(const char*)’:
/home/heif/Srcs/parser/h265parser/h265parser.cpp:109: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:116: error: could not convert ‘std::sort [with _RAIter = __gnu_cxx::__normal_iterator<ParserInterface::PicOrder*, std::vector<ParserInterface::PicOrder, std::allocator<ParserInterface::PicOrder> > >, _Compare = bool (*)(const ParserInterface::PicOrder&, const ParserInterface::PicOrder&)](picOrder.std::vector<_Tp, _Alloc>::begin [with _Tp = ParserInterface::PicOrder, _Alloc = std::allocator<ParserInterface::PicOrder>](), picOrder.std::vector<_Tp, _Alloc>::end [with _Tp = ParserInterface::PicOrder, _Alloc = std::allocator<ParserInterface::PicOrder>](), ParserInterface::compareDecodeOrder)’ to ‘bool’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:118: error: expected primary-expression before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:118: error: expected ‘)’ before ‘for’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:118: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:122: error: could not convert ‘picOrder.std::vector<_Tp, _Alloc>::clear [with _Tp = ParserInterface::PicOrder, _Alloc = std::allocator<ParserInterface::PicOrder>]()’ to ‘bool’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:123: error: expected primary-expression before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:123: error: expected ‘)’ before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:123: error: expected primary-expression before ‘}’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:123: error: expected ‘;’ before ‘}’ token
cc1plus: warnings being treated as errors
/home/heif/Srcs/parser/h265parser/h265parser.cpp:86: error: unused variable ‘displayNum’
/home/heif/Srcs/parser/h265parser/h265parser.cpp: In member function ‘bool H265Parser::hasVpsExtension()’:
/home/heif/Srcs/parser/h265parser/h265parser.cpp:147: error: expected initializer before ‘:’ token
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected primary-expression at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected ‘;’ at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected primary-expression at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected ‘)’ at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected statement at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:146: error: unused variable ‘hasExtension’
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: expected ‘}’ at end of input
/home/heif/Srcs/parser/h265parser/h265parser.cpp:3033: error: no return statement in function returning non-void
make[2]: *** [Srcs/parser/h265parser/CMakeFiles/h265parser.dir/h265parser.cpp.o] Error 1
make[2]: Leaving directory `/home/heif/build'
make[1]: *** [Srcs/parser/h265parser/CMakeFiles/h265parser.dir/all] Error 2
make[1]: Leaving directory `/home/heif/build'
make: *** [all] Error 2

**Comment by guoying1030** [comment]
you must upgrad gcc and g++ to 4.8

**Comment by jieweijasson** [comment]
请问我在centos7上编译通过了，生成了可执行文件，下一步怎么让.heic格式的图片转为jpeg格式？谢谢

**Comment by nokiatech** [comment]
Code requires C++11 support from compiler.
