### ISSUE TITLE
h265parser.cpp undeclared identifier 'log2'

### ISSUE THREAD

**Issue by duowanSir** [nokiatech/heif#26]
D:\android_weiyun_proj\branches\Heif3\app\src\main\cpp\heif\Srcs\parser\h265parser\h265parser.cpp:1832:41: error: use of undeclared identifier 'log2'
              unsigned int numBits = ceil(log2(numLayersInTreePartition.at(j) + 1));
                                          ^
  D:\android_weiyun_proj\branches\Heif3\app\src\main\cpp\heif\Srcs\parser\h265parser\h265parser.cpp:1937:37: error: use of undeclared identifier 'log2'
          unsigned int numBits = ceil(log2(numLayerSets - 1));
                                      ^
  D:\android_weiyun_proj\branches\Heif3\app\src\main\cpp\heif\Srcs\parser\h265parser\h265parser.cpp:2061:45: error: use of undeclared identifier 'log2'
                  unsigned int numBits = ceil(log2(vpsExt.mVpsNumProfileTierLevelMinus1 + 1));
                                              ^
  3 errors generated.
  ninja: build stopped: subcommand failed.

**Comment by nokiatech** [comment]
No longer part of code base in v3.0. Resolved.
