### ISSUE TITLE
Parser SPS crash as SPS struct not init!!

### ISSUE THREAD

**Issue by PhymurByrd** [nokiatech/heif#27]
The SequenceParameterSet is struct type, and not init while new.
 
 if (naluHeader.mH265NalUnitType == H265NalUnitType::SPS){   
    SequenceParameterSet* sps = new SequenceParameterSet;
    **printf("[%s-%d]%p mSpsInferScalingListFlag(%d)\n", __func__, __LINE__, this, sps->mSpsInferScalingListFlag);**
    parseSPS(bitstr, *sps, naluHeader);
    removeSps(sps->mSpsId);
    mSpsList.push_back(sps);
    }

Then print log is:
[parseNalUnit-457]0x7ffeefbfd7e8 mSpsInferScalingListFlag(**66301659**)

**Comment by PhymurByrd** [comment]
should change to 
SequenceParameterSet* sps = new SequenceParameterSet {};   with {} at the end.

**Comment by nokiatech** [comment]
Parsers no longer part of code base since v3.0.
