### ISSUE TITLE
Problems with decoding the 7th tile on JavaScript

### ISSUE THREAD

**Issue by rac-c-o-on** [nokiatech/heif#28]
Problems with decoding the 7th tile. When you try to decode the 7th tile, then there are problems. Here already wrote, how to solve this problem on c++, but nothing about JavaScript.

I tried to rewrite it on the JS, but nothing came out. Is it even possible?
Somebody did the decoding onJavaScript?

![default](https://user-images.githubusercontent.com/19979345/32008216-468a8a32-b9de-11e7-983b-baf1b7255a44.PNG)

**Comment by elsallam-myfiziq** [comment]
this may help
https://stackoverflow.com/questions/45485622/corrupted-heic-tile-when-converting-to-jpeg

**Comment by nokiatech** [comment]
Javascript implementation has been updated to v3.0 reader where this issue has been fixed.

**Comment by introvertautist** [comment]
It doesnt work, сучки :trollface: :shit:
