### ISSUE TITLE
Where is the JavaScript reader?

### ISSUE THREAD

**Issue by warpdesign** [nokiatech/heif#31]
From the README.md:

> HEIF Reader JavaScript Implementation

I couldn't find any `.js` files in the repository.

**Comment by HumayunKaleem** [comment]
https://github.com/nokiatech/heif/wiki

**Comment by warpdesign** [comment]
Js source code is actually found in gh-pages branch.

See: https://github.com/nokiatech/heif/wiki/IV.-HEIF-Reader-JavaScript-Implementation
