### ISSUE TITLE
crash when i use example1()

### ISSUE THREAD

**Issue by linzejia15616** [nokiatech/heif#35]
lzj@lzj:~/jia/mytest/image_process/heif/build$ 
lzj@lzj:~/jia/mytest/image_process/heif/build$ ../Bins/examples 
compatibilityVersion = 0
[MESSAGE][readStream-1036] compatibilityVersion = 0
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
success
terminate called after throwing an instance of 'std::out_of_range'
  what():  `map::at`
Terminated(core dump)

This is a picture sample, and when I use other images in heic format, it's the same mistake;
The environment is ubuntu 14.04;
[IMG_0657.zip](https://github.com/nokiatech/heif/files/1534201/IMG_0657.zip)

**Comment by jieweijasson** [comment]
请问你解决该这个问题了吗
