### ISSUE TITLE
building and installing instructions

### ISSUE THREAD

**Issue by freswa** [nokiatech/heif#43]
Hey,
I am maintaining https://aur.archlinux.org/packages/heif/ but I have troubles updating to the latest v3.0 release.
It would help alot if the README would have some building and installing instructions.
Thanks

**Comment by nokiatech** [comment]
Hi, 
Projects main cmake define (CMakeLists.txt) has moved under heif/srcs so for Linux:
```
cd heif/build
cmake ../srcs
make
```
should be sufficient (presuming compilation tools and cmake exists in enviroment).

Example executable ends up under heif/build/bin/ with libraries under heif/build/lib/
API headers for libraries are under heif/srcs/api/... 

Please note that writerapp (with its avc/hevc parser libraries) executable is no longer part of code base in v3.0 and has been replaced by writer library / API.

Your comment about README has been noted and we will update it with link to wiki:
https://github.com/nokiatech/heif/wiki/I.-How-to-build-HEIF-Source-Code

**Comment by freswa** [comment]
Thanks @nokiatech

**Comment by jieweijasson** [comment]
hi ,how to call writer api?
