### ISSUE TITLE
Fedora 26 - compile error with gcc-c++-7.1.1

### ISSUE THREAD

**Issue by zuzzurro** [nokiatech/heif#6]
I just tried compiling heif fresh from github on my fedora 26 beta pc and the compilation fails with the following error:

```
cd /home/zzz/Downloads/git/heif/build/Srcs/jsonlib && /usr/lib64/ccache/c++    -std=c++11 -Wall -Wextra -Werror -Wno-missing-field-initializers   -o CMakeFiles/json.dir/jsoncpp.cpp.o -c /home/zzz/Downloads/git/heif/Srcs/jsonlib/jsoncpp.cpp
/home/zzz/Downloads/git/heif/Srcs/jsonlib/jsoncpp.cpp: In member function ‘bool Json::OurReader::readToken(Json::OurReader::Token&)’:
/home/zzz/Downloads/git/heif/Srcs/jsonlib/jsoncpp.cpp:1444:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (features_.allowSingleQuotes_) {
     ^~
/home/zzz/Downloads/git/heif/Srcs/jsonlib/jsoncpp.cpp:1449:3: note: here
   case '/':
   ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Srcs/jsonlib/CMakeFiles/json.dir/build.make:66: Srcs/jsonlib/CMakeFiles/json.dir/jsoncpp.cpp.o] Error 1

```

**Comment by Sunting78** [comment]
I have the same problem with you. Have you solved this problem now?

**Comment by kokokranc** [comment]
I'm on windows and compiling from MinGW toolchain, same problem.

Cmake version 3.9.3
MinGW version MinGW-W64-builds-4.3.0

`
cd /d D:\***\Documents\heif-master\build2\Srcs\jsonlib && "D:\Program Files\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev1\mingw64\bin\g++.exe"    -std=c++11 -Wall -Wextra -Werror -Wno-missing-field-initializers   -o CMakeFiles\json.dir\jsoncpp.cpp.obj -c D:\***\Documents\heif-master\Srcs\jsonlib\jsoncpp.cpp
D:\***\Documents\heif-master\Srcs\jsonlib\jsoncpp.cpp: In member function 'bool Json::OurReader::readToken(Json::OurReader::Token&)':
D:\***\Documents\heif-master\Srcs\jsonlib\jsoncpp.cpp:1444:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (features_.allowSingleQuotes_) {
     ^~
D:\***\Documents\heif-master\Srcs\jsonlib\jsoncpp.cpp:1449:3: note: here
   case '/':
   ^~~~
cc1plus.exe: all warnings being treated as errors
Srcs\jsonlib\CMakeFiles\json.dir\build.make:64: recipe for target 'Srcs/jsonlib/CMakeFiles/json.dir/jsoncpp.cpp.obj' failed
mingw32-make[2]: *** [Srcs/jsonlib/CMakeFiles/json.dir/jsoncpp.cpp.obj] Error 1
`

**Comment by avibrazil** [comment]
Exact same problem on Fedora 26.

**Comment by avibrazil** [comment]
Solved. Use clang compiler (LLVM) instead of g++.

On Fedora do this:

`dnf install clang;
cd heif;
CXX=clang++ cmake .;
make`

**Comment by mabushey** [comment]
On Debian/Ubuntu: `apt-get install clang cmake`

**Comment by teknoraver** [comment]
Oh c'mon, changing the compiler when the fix is just inserting a small comment in the code?
I've a pull request to fix this, please consider merging.

**Comment by nokiatech** [comment]
Jsonlib no longer part of code base as of v3.0.
