### ISSUE TITLE
Multiple compile errors with VS 2015

### ISSUE THREAD

**Issue by dgnuff** [nokiatech/heif#7]
There are no Visual Studio project files, so I've had to craft them by hand.  Most of the project is building fine, but I'm getting numerous complaints of the following form:

1>Srcs\writer\datastore.cpp(39): error C2065: 'not': undeclared identifier

where the offending line is:

    if (not mValueMap.count(key))

not is not the boolean negation operator in C++, the standard very clearly defines ! as this operator.  Is there any good reason for attempting to use a non-standard operator, I'm not sure I can see how doing so adds any value to the project.

**Comment by liuziangexit** [comment]
yep i encountered the same problem, probably cause this item does not support MSVC? can  someone teach  me  how to buit this thing in msvc?(sad

**Comment by dgnuff** [comment]
To be honest, this looks to me like the programmer that wrote this learned to program in BASIC, and never bothered to learn C++ properly.

To make matters worse, libheif is only half a solution, if you look at their samples they pull a bitstream out of the file, and then instead of actually having a api that decodes the bitstream to an image, there's a rather cryptic comment that says you have to call something else to do so.  No mention of what you actually call, of course, or what library it's in.

I've simply dropped support for libheif till these two issues get fixed, and I'd very strongly recommend you do the same.  libheif as it currently stands is not anywhere near ready for prime time.

I'm using libbpg from Fabrice Bellard's web site at https://bellard.org/bpg/  It's a complete solution for reading and writing bpg images, no half finished libraries to be found there.  bpgs are based on H.265 compression as are heifs, so the quality vs size parameters will be pretty much the same.  They're just a couple of orders of magnitude easier to work with.

Code compiles correctly under MSVC, and is a complete end to end solution.

**Comment by silverbacknet** [comment]
`not` has been part of the C++ standard since C++98, it's just not very common at all. It automatically works in GCC and clang, but in MSVC you have to `#include <ciso646>`.

**Comment by madadaaa** [comment]
can someone provide a pre-built package for dev? it is too hard to compiled....

**Comment by nokiatech** [comment]
Resolved in v3.0.
