### ISSUE TITLE
example8() could not be run 

### ISSUE THREAD

**Issue by cefengxu** [nokiatech/heif#75]
**PURPOSE:
extract the EXIF information of the image of HEIC FORMAT.**

However, when using example8() to check the exif info from a image , but alway be return when running  to the code below:
```
if (fileInfo.rootMetaBoxInformation.itemInformations[0].itemId != exifItemId)
{
        return;
}
```
i got the output of deferrent id below:
```
fileInfo.rootMetaBoxInformation.itemInformations[0].itemId.mId = 1002
exifItemId.mId = 1004
```

how to deal with this case?

**Comment by wangcen17** [comment]
hi，bro，
I meet the same problem ,too.
have you solved that?

**Comment by lassehe** [comment]
Thank you for reporting this, and sorry for my delayed response. After earlier changes the Exif item was the second element in the array, not anymore the first. Unfortunately I missed updating example.cpp to reflect this.
The newest release v3.6.2 (bdac2fc) improves example.cpp in several ways, and also fixes this issue.
