### ISSUE TITLE
about the example8?

### ISSUE THREAD

**Issue by wangcen17** [nokiatech/heif#78]
why I can not get the exifdata.bin,

when the programm enter 
if (fileInfo.rootMetaBoxInformation.itemInformations[0].itemId != exifItemId)
    {
        return;
 }
it return

**Comment by lassehe** [comment]
Thank you for reporting this, and sorry for my delayed response. As you might have noticed, the example was using here an invalid index (0 instead of 1).
The newest release v3.6.2 (bdac2fc) improves example.cpp in several ways, and also fixes this issue.
